#!/usr/bin/env python3
"""Generate `main/model_weights.h` (C const float arrays) from the bundled
CSI-embedding model, so the ESP32 firmware can run inference on-device.

Reads the same files the hub/Pi use (kept in the desktop crate's resources):
  csi-embed-v2.safetensors  -> w1/bn1/w2/bn2
  presence-head.json        -> presence head (128->1)
  node-1.json               -> default per-room LoRA (rank 4)

Run:  python firmware/esp32-csi-node/tools/gen_model_weights.py
"""
import json
import struct
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.normpath(os.path.join(
    HERE, "..", "..", "..", "rust-port", "wifi-densepose-rs",
    "crates", "wifi-densepose-desktop", "resources", "models"))
OUT = os.path.normpath(os.path.join(HERE, "..", "main", "model_weights.h"))


def load_safetensors(path):
    with open(path, "rb") as f:
        n = struct.unpack("<Q", f.read(8))[0]
        header = json.loads(f.read(n))
        data = f.read()
    tensors = {}
    for name, meta in header.items():
        if name == "__metadata__":
            continue
        s, e = meta["data_offsets"]
        vals = list(struct.unpack(f"<{(e - s) // 4}f", data[s:e]))
        tensors[name] = (meta["shape"], vals)
    return tensors


def carr(name, vals):
    body = ", ".join(f"{v:.8g}f" for v in vals)
    return f"static const float {name}[{len(vals)}] = {{ {body} }};\n"


def main():
    st = load_safetensors(os.path.join(RES, "csi-embed-v2.safetensors"))
    head = json.load(open(os.path.join(RES, "presence-head.json")))
    lora = json.load(open(os.path.join(RES, "node-1.json")))
    la = [x for row in lora["weights"]["loraA"] for x in row]  # [128*4]
    lb = [x for row in lora["weights"]["loraB"] for x in row]  # [4*128]

    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_model_weights.py -- do not edit.\n")
        f.write("// CSI-embedding model (8->64->128 MLP + BN + LoRA + presence head).\n")
        f.write("#pragma once\n\n")
        f.write("#define CSI_IN 8\n#define CSI_HID 64\n#define CSI_EMB 128\n#define CSI_LORA_RANK 4\n\n")
        f.write(carr("CSI_W1", st["w1.weight"][1]))       # [64*8]
        f.write(carr("CSI_B1", st["w1.bias"][1]))         # [64]
        f.write(carr("CSI_BN1_G", st["bn1.weight"][1]))
        f.write(carr("CSI_BN1_B", st["bn1.bias"][1]))
        f.write(carr("CSI_BN1_M", st["bn1.running_mean"][1]))
        f.write(carr("CSI_BN1_V", st["bn1.running_var"][1]))
        f.write(carr("CSI_W2", st["w2.weight"][1]))       # [128*64]
        f.write(carr("CSI_B2", st["w2.bias"][1]))         # [128]
        f.write(carr("CSI_BN2_G", st["bn2.weight"][1]))
        f.write(carr("CSI_BN2_B", st["bn2.bias"][1]))
        f.write(carr("CSI_BN2_M", st["bn2.running_mean"][1]))
        f.write(carr("CSI_BN2_V", st["bn2.running_var"][1]))
        f.write(carr("CSI_LORA_A", la))                   # [128*4]
        f.write(carr("CSI_LORA_B", lb))                   # [4*128]
        f.write(f"static const float CSI_LORA_SCALE = {lora['weights']['scaling']:.8g}f;\n")
        f.write(carr("CSI_HEAD_W", head["weights"]))      # [128]
        f.write(f"static const float CSI_HEAD_B = {head['bias']:.8g}f;\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
