//! Native ESP-IDF NVS partition binary generator (no Python dependency).
//!
//! Implements the subset of the ESP-IDF NVS (Non-Volatile Storage) v2
//! "multipage" binary format needed to provision an ESP32 CSI node's
//! `csi_cfg` namespace with the WiFi/target keys the firmware reads in
//! `firmware/esp32-csi-node/main/nvs_config.c`.
//!
//! The output is a `0x6000`-byte (24 KiB) image, byte-for-byte identical to
//! what ESP-IDF's `esp_idf_nvs_partition_gen generate <csv> <bin> 0x6000`
//! produces for the same key set, so the operator no longer needs Python
//! installed to run the in-app provisioning flow. The
//! `tests/fixtures/nvs_csi_cfg_golden.bin` golden fixture (generated by that
//! tool) is asserted byte-for-byte by the unit tests below.
//!
//! ## Full-replace semantics (issue #391)
//!
//! Flashing this image to NVS offset `0x9000` REPLACES the entire `csi_cfg`
//! namespace — there is no merge with whatever is already on the device.
//! [`Esp32NvsConfig`] therefore requires the full WiFi trio so the wizard
//! path can never silently wipe credentials.
//!
//! ## Format reference (reverse-engineered from the golden fixture)
//!
//! * Partition = N × 4096-byte **pages**. We populate page 0 and leave the
//!   remaining pages `0xff`-filled (uninitialised), matching the generator.
//! * Page layout: 32-byte **header** + 32-byte **entry-state bitmap** +
//!   126 × 32-byte **entries**.
//! * Header: `state`(4, LE `0xfffffffe` = ACTIVE) + `seq_number`(4, LE) +
//!   `version`(1, `0xfe` = v2) + `unused`(19, `0xff`) + `crc32`(4, over
//!   bytes `[4..28]`).
//! * Bitmap: 2 bits per entry, LSB-first; `0b10` (=2) written, `0b11` (=3)
//!   empty. So a written entry contributes `0xaa`-style bytes.
//! * Entry (32 bytes): `NS`(1) + `Type`(1) + `Span`(1) + `ChunkIndex`(1) +
//!   `CRC32`(4, over the 28 bytes = header `[0..4]` ++ key ++ data) +
//!   `Key`(16, NUL-terminated, `0xff`-padded) + `Data`(8).
//! * Namespace entry: `NS=0`, `Type=U8(0x01)`, `Key="csi_cfg"`, data byte 0
//!   holds the namespace index (1); remaining 7 data bytes `0xff`.
//! * Primitive entry (U8/U16): `NS=<ns index>`, `Span=1`, `ChunkIndex=0xff`,
//!   data holds the little-endian value, remaining data bytes `0xff`.
//! * String entry: `NS=<ns index>`, `Type=STR(0x21)`, `Span=1+ceil(len/32)`,
//!   `ChunkIndex=0xff`, data = `size`(2, LE, = `strlen+1` incl NUL) +
//!   `reserved`(2, `0xffff`) + `crc32`(4, over the NUL-terminated body).
//!   The body follows in the next `Span-1` entry slots, `0xff`-padded.
//!
//! CRC32 here follows ESP-IDF's NVS convention (`zlib.crc32(data, 0xffffffff)`):
//! the standard reflected CRC-32/ISO-HDLC table algorithm with the running
//! register seeded at `0` and the usual final `^ 0xffffffff` applied. See
//! [`crc32_le`] and the golden test for the empirical grounding.

use serde::{Deserialize, Serialize};

use crate::domain::config::ProvisioningConfig;

/// Total NVS partition size we emit (24 KiB), matching the ESP-IDF standard
/// 4 MB partition table's `nvs` partition and provision.py's `NVS_PARTITION_SIZE`.
pub const NVS_PARTITION_SIZE: usize = 0x6000;

/// One NVS page is 4096 bytes.
const PAGE_SIZE: usize = 4096;

/// Each entry (and the page header, and each bitmap slot) is 32 bytes.
const ENTRY_SIZE: usize = 32;

/// The page header occupies the first 32-byte slot of a page.
const PAGE_HEADER_SIZE: usize = ENTRY_SIZE;

/// The entry-state bitmap occupies the second 32-byte slot (2 bits per entry
/// × 126 entries = 252 bits, rounded up to 32 bytes).
const BITMAP_SIZE: usize = ENTRY_SIZE;

/// Byte offset of the first entry within a page (after header + bitmap).
const ENTRIES_OFFSET: usize = PAGE_HEADER_SIZE + BITMAP_SIZE;

/// Entries per page after the header and bitmap slots.
const ENTRIES_PER_PAGE: usize = (PAGE_SIZE - ENTRIES_OFFSET) / ENTRY_SIZE;

/// NVS item type tags (subset).
const TYPE_U8: u8 = 0x01;
const TYPE_U16: u8 = 0x02;
const TYPE_STR: u8 = 0x21;

/// Namespace index assigned to `csi_cfg` (first and only namespace).
const NS_INDEX: u8 = 1;

/// Flash-default byte for unwritten regions.
const FF: u8 = 0xff;

/// Configuration for the `csi_cfg` NVS namespace.
///
/// The WiFi trio (`ssid`, `password`, `target_ip`) is mandatory: writing this
/// image is full-replace, so a partial config would erase credentials on the
/// device (issue #391). Optional keys map to the firmware defaults when absent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Esp32NvsConfig {
    /// WiFi SSID (2.4 GHz network the node joins).
    pub ssid: String,
    /// WiFi password (may be empty for open networks, but must be provided).
    pub password: String,
    /// Aggregator/hub IP the node streams CSI to.
    pub target_ip: String,
    /// Aggregator UDP port (firmware default 5005).
    pub target_port: u16,
    /// Node identifier (0-255).
    pub node_id: u8,
    /// Optional TDM slot index for this node (0-based).
    pub tdm_slot: Option<u8>,
    /// Optional total node count in the TDM schedule.
    pub tdm_nodes: Option<u8>,
}

impl Esp32NvsConfig {
    /// Validate provisioning invariants before generating the image.
    ///
    /// * `target_port` must be non-zero.
    /// * `tdm_slot`/`tdm_nodes` must be supplied together and `slot < nodes`
    ///   (matches provision.py and the firmware's clamp warning).
    /// * String lengths must fit the firmware buffers (`nvs_config.h`).
    pub fn validate(&self) -> Result<(), String> {
        if self.ssid.is_empty() {
            return Err("ssid must not be empty".into());
        }
        if self.target_ip.is_empty() {
            return Err("target_ip must not be empty".into());
        }
        if self.target_port == 0 {
            return Err("target_port must be non-zero".into());
        }
        // Firmware buffers: SSID 33, password 65, IP 16 (incl NUL).
        if self.ssid.len() > 32 {
            return Err(format!("ssid too long ({} > 32 chars)", self.ssid.len()));
        }
        if self.password.len() > 64 {
            return Err(format!(
                "password too long ({} > 64 chars)",
                self.password.len()
            ));
        }
        if self.target_ip.len() > 15 {
            return Err(format!(
                "target_ip too long ({} > 15 chars)",
                self.target_ip.len()
            ));
        }
        match (self.tdm_slot, self.tdm_nodes) {
            (Some(_), None) | (None, Some(_)) => {
                return Err("tdm_slot and tdm_nodes must be set together".into());
            }
            (Some(slot), Some(nodes)) => {
                if nodes == 0 {
                    return Err("tdm_nodes must be >= 1".into());
                }
                if slot >= nodes {
                    return Err(format!(
                        "tdm_slot ({slot}) must be less than tdm_nodes ({nodes})"
                    ));
                }
            }
            (None, None) => {}
        }
        Ok(())
    }

    /// Build from the desktop's richer [`ProvisioningConfig`], mapping the
    /// subset the native generator writes. Errors if the WiFi trio is missing.
    pub fn from_provisioning(cfg: &ProvisioningConfig) -> Result<Self, String> {
        Ok(Self {
            ssid: cfg
                .wifi_ssid
                .clone()
                .ok_or("wifi_ssid is required for NVS provisioning")?,
            password: cfg.wifi_password.clone().unwrap_or_default(),
            target_ip: cfg
                .target_ip
                .clone()
                .ok_or("target_ip is required for NVS provisioning")?,
            target_port: cfg.target_port.unwrap_or(5005),
            node_id: cfg.node_id.unwrap_or(1),
            tdm_slot: cfg.tdm_slot,
            tdm_nodes: cfg.tdm_total,
        })
    }
}

/// A single logical NVS entry to be laid out on a page. String entries expand
/// into multiple 32-byte slots (header slot + body slots).
enum Item {
    Namespace,
    U8 { key: &'static str, value: u8 },
    U16 { key: &'static str, value: u16 },
    Str { key: &'static str, value: String },
}

/// Generate the `csi_cfg` NVS partition image for `cfg`.
///
/// Returns a [`NVS_PARTITION_SIZE`]-byte image ready to flash at offset
/// `0x9000`. The byte layout matches ESP-IDF's generator for the same keys
/// (see the golden test).
pub fn generate_nvs_csi_cfg(cfg: &Esp32NvsConfig) -> Result<Vec<u8>, String> {
    cfg.validate()?;

    // Assemble the logical items in the same order provision.py's
    // build_nvs_csv writes them (namespace first, then keys), which is the
    // order ESP-IDF lays entries out and thus what the golden fixture uses.
    let mut items: Vec<Item> = vec![
        Item::Namespace,
        Item::Str {
            key: "ssid",
            value: cfg.ssid.clone(),
        },
        Item::Str {
            key: "password",
            value: cfg.password.clone(),
        },
        Item::Str {
            key: "target_ip",
            value: cfg.target_ip.clone(),
        },
        Item::U16 {
            key: "target_port",
            value: cfg.target_port,
        },
        Item::U8 {
            key: "node_id",
            value: cfg.node_id,
        },
    ];
    if let (Some(slot), Some(nodes)) = (cfg.tdm_slot, cfg.tdm_nodes) {
        items.push(Item::U8 {
            key: "tdm_slot",
            value: slot,
        });
        items.push(Item::U8 {
            key: "tdm_nodes",
            value: nodes,
        });
    }

    // Render each item into its 32-byte entry slots.
    let mut entries: Vec<[u8; ENTRY_SIZE]> = Vec::new();
    for item in &items {
        render_item(item, &mut entries)?;
    }

    if entries.len() > ENTRIES_PER_PAGE {
        return Err(format!(
            "NVS config too large: {} entries exceed one page ({})",
            entries.len(),
            ENTRIES_PER_PAGE
        ));
    }

    let mut image = vec![FF; NVS_PARTITION_SIZE];
    write_page0(&mut image, &entries);
    Ok(image)
}

/// Render one logical item into one or more 32-byte entry slots.
fn render_item(item: &Item, out: &mut Vec<[u8; ENTRY_SIZE]>) -> Result<(), String> {
    match item {
        Item::Namespace => {
            // NS=0, Type=U8, key="csi_cfg", data[0]=namespace index.
            let mut data = [FF; 8];
            data[0] = NS_INDEX;
            out.push(build_entry(0, TYPE_U8, 1, 0xff, "csi_cfg", &data));
        }
        Item::U8 { key, value } => {
            let mut data = [FF; 8];
            data[0] = *value;
            out.push(build_entry(NS_INDEX, TYPE_U8, 1, 0xff, key, &data));
        }
        Item::U16 { key, value } => {
            let mut data = [FF; 8];
            data[0..2].copy_from_slice(&value.to_le_bytes());
            out.push(build_entry(NS_INDEX, TYPE_U16, 1, 0xff, key, &data));
        }
        Item::Str { key, value } => {
            // Body is the string plus a trailing NUL.
            let mut body = value.as_bytes().to_vec();
            body.push(0);
            let size = body.len();
            if size > u16::MAX as usize {
                return Err(format!("string '{key}' too long ({size} bytes)"));
            }
            let body_slots = size.div_ceil(ENTRY_SIZE);
            let span = 1 + body_slots as u8;

            // Header entry data: size(2) + reserved(2, 0xffff) + crc32(4, body).
            let mut data = [FF; 8];
            data[0..2].copy_from_slice(&(size as u16).to_le_bytes());
            // data[2..4] stay 0xff (reserved).
            let body_crc = crc32_le(&body);
            data[4..8].copy_from_slice(&body_crc.to_le_bytes());
            out.push(build_entry(NS_INDEX, TYPE_STR, span, 0xff, key, &data));

            // Body slots, 0xff-padded.
            for chunk in body.chunks(ENTRY_SIZE) {
                let mut slot = [FF; ENTRY_SIZE];
                slot[..chunk.len()].copy_from_slice(chunk);
                out.push(slot);
            }
        }
    }
    Ok(())
}

/// Build a 32-byte entry from its fields, computing the per-entry CRC32.
fn build_entry(
    ns: u8,
    item_type: u8,
    span: u8,
    chunk_index: u8,
    key: &str,
    data: &[u8; 8],
) -> [u8; ENTRY_SIZE] {
    let mut e = [FF; ENTRY_SIZE];
    e[0] = ns;
    e[1] = item_type;
    e[2] = span;
    e[3] = chunk_index;
    // e[4..8] = CRC, filled below.
    // Key: 16-byte field, NUL-terminated and **zero-padded** (verified against
    // the golden fixture — the padding is 0x00, not 0xff).
    e[8..24].fill(0);
    let kbytes = key.as_bytes();
    let klen = kbytes.len().min(15); // leave room for the NUL within 16
    e[8..8 + klen].copy_from_slice(&kbytes[..klen]);
    // e[8 + klen] stays 0 (NUL terminator); remaining key bytes stay 0.
    e[24..32].copy_from_slice(data);

    // CRC32 over header[0..4] ++ key[8..24] ++ data[24..32] (28 bytes),
    // i.e. everything except the CRC field itself.
    let mut crc_input = [0u8; 28];
    crc_input[0..4].copy_from_slice(&e[0..4]);
    crc_input[4..20].copy_from_slice(&e[8..24]);
    crc_input[20..28].copy_from_slice(&e[24..32]);
    let crc = crc32_le(&crc_input);
    e[4..8].copy_from_slice(&crc.to_le_bytes());
    e
}

/// Write page 0 (header + bitmap + entries) into the image. Remaining pages
/// stay `0xff` (uninitialised), matching the ESP-IDF generator.
fn write_page0(image: &mut [u8], entries: &[[u8; ENTRY_SIZE]]) {
    // --- Page header (bytes 0..32) ---
    // state = ACTIVE = 0xfffffffe (LE)
    image[0..4].copy_from_slice(&0xffff_fffe_u32.to_le_bytes());
    // seq_number = 0
    image[4..8].copy_from_slice(&0u32.to_le_bytes());
    // version = 0xfe (NVS format v2)
    image[8] = 0xfe;
    // unused bytes [9..28] stay 0xff.
    for b in image.iter_mut().take(28).skip(9) {
        *b = FF;
    }
    // header CRC over bytes [4..28]
    let hdr_crc = crc32_le(&image[4..28]);
    image[28..32].copy_from_slice(&hdr_crc.to_le_bytes());

    // --- Entry state bitmap (the slot after the header): 2 bits per entry,
    // LSB-first. written = 0b10 (2), empty = 0b11 (3). Start all-empty (0xff)
    // then mark each written entry.
    for b in image
        .iter_mut()
        .take(ENTRIES_OFFSET)
        .skip(PAGE_HEADER_SIZE)
    {
        *b = FF;
    }
    for (i, _) in entries.iter().enumerate() {
        let byte = PAGE_HEADER_SIZE + i / 4;
        let shift = (i % 4) * 2;
        // Clear the two bits (set to 0b00) then OR in 0b10 -> written(2).
        image[byte] &= !(0b11 << shift);
        image[byte] |= 0b10 << shift;
    }

    // --- Entries (after header + bitmap) ---
    for (i, entry) in entries.iter().enumerate() {
        let off = ENTRIES_OFFSET + i * ENTRY_SIZE;
        // All entries fit in one page by construction (checked by caller).
        image[off..off + ENTRY_SIZE].copy_from_slice(entry);
    }
}

/// Canonical reflected CRC-32 lookup table (polynomial `0xEDB88820`), i.e. the
/// zlib/CRC-32/ISO-HDLC table. `CRC32_TABLE[1] == 0x77073096`. Embedded as a
/// literal (rather than computed) so it is trivially auditable against any
/// reference table and cannot drift from the golden fixture.
#[rustfmt::skip]
const CRC32_TABLE: [u32; 256] = [
    0x00000000, 0x77073096, 0xee0e612c, 0x990951ba, 0x076dc419, 0x706af48f, 0xe963a535, 0x9e6495a3,
    0x0edb8832, 0x79dcb8a4, 0xe0d5e91e, 0x97d2d988, 0x09b64c2b, 0x7eb17cbd, 0xe7b82d07, 0x90bf1d91,
    0x1db71064, 0x6ab020f2, 0xf3b97148, 0x84be41de, 0x1adad47d, 0x6ddde4eb, 0xf4d4b551, 0x83d385c7,
    0x136c9856, 0x646ba8c0, 0xfd62f97a, 0x8a65c9ec, 0x14015c4f, 0x63066cd9, 0xfa0f3d63, 0x8d080df5,
    0x3b6e20c8, 0x4c69105e, 0xd56041e4, 0xa2677172, 0x3c03e4d1, 0x4b04d447, 0xd20d85fd, 0xa50ab56b,
    0x35b5a8fa, 0x42b2986c, 0xdbbbc9d6, 0xacbcf940, 0x32d86ce3, 0x45df5c75, 0xdcd60dcf, 0xabd13d59,
    0x26d930ac, 0x51de003a, 0xc8d75180, 0xbfd06116, 0x21b4f4b5, 0x56b3c423, 0xcfba9599, 0xb8bda50f,
    0x2802b89e, 0x5f058808, 0xc60cd9b2, 0xb10be924, 0x2f6f7c87, 0x58684c11, 0xc1611dab, 0xb6662d3d,
    0x76dc4190, 0x01db7106, 0x98d220bc, 0xefd5102a, 0x71b18589, 0x06b6b51f, 0x9fbfe4a5, 0xe8b8d433,
    0x7807c9a2, 0x0f00f934, 0x9609a88e, 0xe10e9818, 0x7f6a0dbb, 0x086d3d2d, 0x91646c97, 0xe6635c01,
    0x6b6b51f4, 0x1c6c6162, 0x856530d8, 0xf262004e, 0x6c0695ed, 0x1b01a57b, 0x8208f4c1, 0xf50fc457,
    0x65b0d9c6, 0x12b7e950, 0x8bbeb8ea, 0xfcb9887c, 0x62dd1ddf, 0x15da2d49, 0x8cd37cf3, 0xfbd44c65,
    0x4db26158, 0x3ab551ce, 0xa3bc0074, 0xd4bb30e2, 0x4adfa541, 0x3dd895d7, 0xa4d1c46d, 0xd3d6f4fb,
    0x4369e96a, 0x346ed9fc, 0xad678846, 0xda60b8d0, 0x44042d73, 0x33031de5, 0xaa0a4c5f, 0xdd0d7cc9,
    0x5005713c, 0x270241aa, 0xbe0b1010, 0xc90c2086, 0x5768b525, 0x206f85b3, 0xb966d409, 0xce61e49f,
    0x5edef90e, 0x29d9c998, 0xb0d09822, 0xc7d7a8b4, 0x59b33d17, 0x2eb40d81, 0xb7bd5c3b, 0xc0ba6cad,
    0xedb88320, 0x9abfb3b6, 0x03b6e20c, 0x74b1d29a, 0xead54739, 0x9dd277af, 0x04db2615, 0x73dc1683,
    0xe3630b12, 0x94643b84, 0x0d6d6a3e, 0x7a6a5aa8, 0xe40ecf0b, 0x9309ff9d, 0x0a00ae27, 0x7d079eb1,
    0xf00f9344, 0x8708a3d2, 0x1e01f268, 0x6906c2fe, 0xf762575d, 0x806567cb, 0x196c3671, 0x6e6b06e7,
    0xfed41b76, 0x89d32be0, 0x10da7a5a, 0x67dd4acc, 0xf9b9df6f, 0x8ebeeff9, 0x17b7be43, 0x60b08ed5,
    0xd6d6a3e8, 0xa1d1937e, 0x38d8c2c4, 0x4fdff252, 0xd1bb67f1, 0xa6bc5767, 0x3fb506dd, 0x48b2364b,
    0xd80d2bda, 0xaf0a1b4c, 0x36034af6, 0x41047a60, 0xdf60efc3, 0xa867df55, 0x316e8eef, 0x4669be79,
    0xcb61b38c, 0xbc66831a, 0x256fd2a0, 0x5268e236, 0xcc0c7795, 0xbb0b4703, 0x220216b9, 0x5505262f,
    0xc5ba3bbe, 0xb2bd0b28, 0x2bb45a92, 0x5cb36a04, 0xc2d7ffa7, 0xb5d0cf31, 0x2cd99e8b, 0x5bdeae1d,
    0x9b64c2b0, 0xec63f226, 0x756aa39c, 0x026d930a, 0x9c0906a9, 0xeb0e363f, 0x72076785, 0x05005713,
    0x95bf4a82, 0xe2b87a14, 0x7bb12bae, 0x0cb61b38, 0x92d28e9b, 0xe5d5be0d, 0x7cdcefb7, 0x0bdbdf21,
    0x86d3d2d4, 0xf1d4e242, 0x68ddb3f8, 0x1fda836e, 0x81be16cd, 0xf6b9265b, 0x6fb077e1, 0x18b74777,
    0x88085ae6, 0xff0f6a70, 0x66063bca, 0x11010b5c, 0x8f659eff, 0xf862ae69, 0x616bffd3, 0x166ccf45,
    0xa00ae278, 0xd70dd2ee, 0x4e048354, 0x3903b3c2, 0xa7672661, 0xd06016f7, 0x4969474d, 0x3e6e77db,
    0xaed16a4a, 0xd9d65adc, 0x40df0b66, 0x37d83bf0, 0xa9bcae53, 0xdebb9ec5, 0x47b2cf7f, 0x30b5ffe9,
    0xbdbdf21c, 0xcabac28a, 0x53b39330, 0x24b4a3a6, 0xbad03605, 0xcdd70693, 0x54de5729, 0x23d967bf,
    0xb3667a2e, 0xc4614ab8, 0x5d681b02, 0x2a6f2b94, 0xb40bbe37, 0xc30c8ea1, 0x5a05df1b, 0x2d02ef8d,
];

/// ESP-IDF NVS entry CRC convention.
///
/// Empirically (verified against the ESP-IDF-generated golden fixture) this is
/// `zlib.crc32(data, 0xffffffff)`: the standard reflected CRC-32 table
/// algorithm with the running register **seeded at 0** and the usual final
/// `^ 0xffffffff` applied. (Seeding at 0 rather than `0xffffffff` is what the
/// `0xffffffff` continuation argument reduces to.)
fn crc32_le(data: &[u8]) -> u32 {
    let mut crc: u32 = 0x0000_0000;
    for &byte in data {
        let idx = ((crc ^ byte as u32) & 0xff) as usize;
        crc = (crc >> 8) ^ CRC32_TABLE[idx];
    }
    crc ^ 0xffff_ffff
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The golden fixture config — must match the CSV committed at
    /// `tests/fixtures/nvs_csi_cfg_golden.csv` and the binary generated from it
    /// by ESP-IDF's `esp_idf_nvs_partition_gen`.
    fn golden_config() -> Esp32NvsConfig {
        Esp32NvsConfig {
            ssid: "RuViewTest".into(),
            password: "test1234".into(),
            target_ip: "192.168.1.20".into(),
            target_port: 5005,
            node_id: 1,
            tdm_slot: None,
            tdm_nodes: None,
        }
    }

    /// The compile-time table must be the canonical reflected CRC-32 table.
    #[test]
    fn crc32_table_is_canonical() {
        assert_eq!(CRC32_TABLE[0], 0x0000_0000);
        assert_eq!(CRC32_TABLE[1], 0x7707_3096);
        assert_eq!(CRC32_TABLE[255], 0x2d02_ef8d);
    }

    /// crc32_le must match ESP-IDF's NVS convention, i.e.
    /// `zlib.crc32(data, 0xffffffff)`. Reference values computed with Python
    /// zlib and verified byte-for-byte against the golden fixture.
    #[test]
    fn crc32_le_matches_nvs_convention() {
        // zlib.crc32(b"123456789", 0xffffffff) == 0xd202d277
        assert_eq!(crc32_le(b"123456789"), 0xd202_d277);
        // zlib.crc32(b"", 0xffffffff) == 0xffffffff
        assert_eq!(crc32_le(b""), 0xffff_ffff);
    }

    /// GOLDEN TEST: our generator must byte-for-byte reproduce ESP-IDF's
    /// output for the WiFi-trio + port + node_id fixture. This is the
    /// correctness proof for the whole NVS format implementation; it is
    /// hermetic (no Python, no network — the .bin is embedded).
    #[test]
    fn generate_matches_esp_idf_golden_byte_for_byte() {
        let golden: &[u8] = include_bytes!("../../tests/fixtures/nvs_csi_cfg_golden.bin");
        let ours = generate_nvs_csi_cfg(&golden_config()).expect("generation");

        assert_eq!(
            ours.len(),
            golden.len(),
            "image size mismatch: {} vs {}",
            ours.len(),
            golden.len()
        );

        if ours != golden {
            // Report the first divergence to make failures debuggable.
            let first = ours
                .iter()
                .zip(golden.iter())
                .position(|(a, b)| a != b)
                .unwrap();
            panic!(
                "NVS image diverges from golden at offset 0x{:x}: ours={:#04x} golden={:#04x}",
                first, ours[first], golden[first]
            );
        }
    }

    /// GOLDEN TEST (multi-slot string + TDM keys): a 46-char password spans two
    /// body slots (span=4), and the TDM keys append two more primitive entries.
    /// This is the only coverage for the `span >= 3` string path and for the
    /// tdm_slot/tdm_nodes byte layout — both absent from the primary fixture.
    #[test]
    fn generate_matches_esp_idf_golden_multislot_and_tdm() {
        let golden: &[u8] = include_bytes!("../../tests/fixtures/nvs_csi_cfg_long.bin");
        let cfg = Esp32NvsConfig {
            ssid: "RuViewTest".into(),
            password: "correcthorsebatterystaple-verylongpassphrase12".into(),
            target_ip: "192.168.1.20".into(),
            target_port: 5005,
            node_id: 1,
            tdm_slot: Some(1),
            tdm_nodes: Some(4),
        };
        // Sanity: this password really does span multiple body slots.
        assert!(cfg.password.len() + 1 > super::ENTRY_SIZE);

        let ours = generate_nvs_csi_cfg(&cfg).expect("generation");
        if ours != golden {
            let first = ours
                .iter()
                .zip(golden.iter())
                .position(|(a, b)| a != b)
                .unwrap();
            panic!(
                "multi-slot NVS image diverges from golden at offset 0x{:x}: ours={:#04x} golden={:#04x}",
                first, ours[first], golden[first]
            );
        }
    }

    #[test]
    fn output_is_partition_sized() {
        let ours = generate_nvs_csi_cfg(&golden_config()).unwrap();
        assert_eq!(ours.len(), NVS_PARTITION_SIZE);
    }

    #[test]
    fn validate_rejects_empty_ssid() {
        let mut cfg = golden_config();
        cfg.ssid = String::new();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn validate_rejects_zero_port() {
        let mut cfg = golden_config();
        cfg.target_port = 0;
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn validate_rejects_bad_tdm() {
        let mut cfg = golden_config();
        cfg.tdm_slot = Some(3);
        cfg.tdm_nodes = Some(2);
        assert!(cfg.validate().is_err());

        let mut cfg2 = golden_config();
        cfg2.tdm_slot = Some(0);
        cfg2.tdm_nodes = None;
        assert!(cfg2.validate().is_err());
    }

    /// With TDM keys present the image still generates and stays single-page.
    #[test]
    fn generate_with_tdm_keys() {
        let mut cfg = golden_config();
        cfg.tdm_slot = Some(1);
        cfg.tdm_nodes = Some(4);
        let img = generate_nvs_csi_cfg(&cfg).unwrap();
        assert_eq!(img.len(), NVS_PARTITION_SIZE);
        // Page 0 header state byte marks ACTIVE.
        assert_eq!(img[0], 0xfe);
    }

    #[test]
    fn from_provisioning_maps_subset() {
        let mut pc = ProvisioningConfig::default();
        pc.wifi_ssid = Some("Net".into());
        pc.wifi_password = Some("pw".into());
        pc.target_ip = Some("10.0.0.1".into());
        let cfg = Esp32NvsConfig::from_provisioning(&pc).unwrap();
        assert_eq!(cfg.target_port, 5005); // default
        assert_eq!(cfg.node_id, 1); // default
    }
}
