// On-device CSI-embedding model inference for the ESP32-S3.
//
// Runs the same 8->64->128 MLP + BatchNorm + per-room LoRA + presence head as
// the hub (wifi-densepose-edge-infer) and the Pi agent. Weights are embedded via
// model_weights.h (generated by tools/gen_model_weights.py). ~9,900 MACs — a few
// microseconds on the S3; fp32 weights fit SRAM with room to spare.
#pragma once
#include <stdint.h>

// Input features, canonical order (scripts/deep-scan.js):
//   [0]=presence [1]=motion [2]=breathing [3]=heart_rate
//   [4]=phase_var [5]=persons [6]=fall [7]=rssi
// Returns presence probability in [0,1]. If `embedding_out` is non-NULL it is
// filled with the 128-d (room-adapted) embedding.
float csi_model_presence(const float in[8], float *embedding_out);
